name: AWSMockBuild
on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          mvn clean install -DskipTests

      - name: Build Docker
        run: |
          VERSION=$(git sv cv)
          cd docker 
          docker build --no-cache --build-arg GH_TOKEN=${GH_TOKEN} -t awsmock:$VERSION .

  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: self-hosted
    needs: [ build ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag images
        run: |
          VERSION=$(git sv cv)
          docker tag awsmock:$VERSION ${{ secrets.DOCKER_USER }}/awsmock:$VERSION
          docker push ${{ secrets.DOCKER_USER }}/awsmock:$VERSION
          docker tag awsmock:$VERSION ${{ secrets.DOCKER_USER }}/awsmock:latest
          docker push ${{ secrets.DOCKER_USER }}/awsmock:latest
